
# PowerShell 5.0 Image
os: WMF 5

# Clone Directory
clone_folder: C:\Projects\ScriptConfig

# Install Pester
install: 
    - cinst -y pester --version 3.3.14

# Module Version
version: 1.0.{build}

# Build only dev and master, tags
skip_tags: true
branches:
  only:
  - master
  - dev

# Execute build script
build_script:
- ps: .\Scripts\build.ps1

# Execute test script
test_script:
- ps: .\Scripts\test.ps1
